### ISSUE TITLE
give options for build triggers in the templates

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/workflows#13]
build triggers are likely a tricky topic for new users. Provide a manual trigger as a default and an alternative such as:
```
  push:
    branches: [main, master]
```

**Comment by k-doering-NOAA** [comment]
thanks @kellijohnson-NOAA for suggesting this!

**Comment by k-doering-NOAA** [comment]
I decided instead to provide the most applicable trigger to the template, rather than a manual trigger, as I think this will create less confusion. Also linked the documentation for the build triggers to help users find different options, if they want.

**Comment by Rick-Methot-NOAA** [comment]
Let's provide the whole team an overview/walk-through of this at next meeting.

**Comment by k-doering-NOAA** [comment]
Good suggestion, Rick - added to the agenda.
