### ISSUE TITLE
Error in yaml syntax (call-r-cmd-check.yml) on line 12

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [nmfs-stock-synthesis/workflows#14]
Thanks for creating nice reusable workflows! I am using the `workflows::use_r_cmd_check()` to create call-r-cmd-check.yml for r4MAS, but the created workflow file is invalid according to the [GitHub Actions summary](https://github.com/nmfs-fish-tools/r4MAS/actions/runs/1545826868/workflow). 

**Potential cause of error**: `workflows::use_r_cmd_check()` creates a workflow using the template of call-r-cmd-check.yml from inst/templates. The yaml file needs extra spaces before "uses" in [the last line](https://raw.githubusercontent.com/nmfs-stock-synthesis/workflows/main/inst/templates/call-r-cmd-check.yml). 

**Potential solutions**: 1) Add extra spaces before "uses" in line 12 in inst/templates/call-r-cmd-check.yml; or 2) update the [url link](https://github.com/nmfs-stock-synthesis/workflows/blob/d7b9a0e0e06dcb5693cead4ee25266918c645d87/R/use_r_workflows.R#L5) in the R script to [https://raw.githubusercontent.com/nmfs-stock-synthesis/workflows/main/.github/workflows/call-r-cmd-check.yml](https://raw.githubusercontent.com/nmfs-stock-synthesis/workflows/main/.github/workflows/call-r-cmd-check.yml)

The reusable workflow works after I added the extra spaces to the call-r-cmd-check.yml manually. Let me know if there are other solutions. Thanks!

**Comment by k-doering-NOAA** [comment]
Thanks @Bai-Li-NOAA ! I think I copied and pasted the workflow from somewhere else and the spacing must have gotten messed up during that. Thanks so much for pointing out this issue! It should now be fixed
