### ISSUE TITLE
create a pull request template

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nmfs-stock-synthesis/workflows#17]
* [GitHub advice on pull request templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
* [GitHub advice on creating community, i.e., organization-level templates](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file)
* [Example files on GitHub](https://github.com/stevemao/github-issue-templates)

**Comment by k-doering-NOAA** [comment]
Thanks @kellijohnson-NOAA ! If you have the time, please feel free to put one together, as you have the most experience with templates out of all of us.  Thanks for suggesting this!

**Comment by k-doering-NOAA** [comment]
It looks like setting this up is as easy as adding a file called PULL_REQUEST_TEMPLATE.md to the .github folder (this could also go in the root directory, but I like adding it to the .github folder better).

So, we need to decide what to put in the template. I'll take a stab at this first. Feel free to edit my comment or propose changes in following comments:

## What issue(s) does this PR address? Describe and add issue numbers, if applicable.

## What tests have been done? Upload any model input files created for testing in a zip file, if possible.

## What tests/review still need to be done? Who can do it, and by when is it needed (ideally)?

## Check which is true. This PR requires:

- [ ] Changes in r4ss
- [ ] Changes to SS3 manual
- [ ] Changes to SSI (the SS3 GUI)

##  Describe any changes in r4ss/SS3 manual/SSI that are needed (if checked):

**Comment by k-doering-NOAA** [comment]
@Rick-Methot-NOAA , your comments on this would be esp. appreciated since you are the main person opening PRs!

**Comment by k-doering-NOAA** [comment]
Some sample issue templates that Kelli (I think) created: https://github.com/nwfsc-assess/PacFIN.Utilities/tree/master/.github/ISSUE_TEMPLATE

**Comment by Rick-Methot-NOAA** [comment]
Very nice start.  I think this will be useful and will comment in detail later.
Perhaps add reminder to link the PR to issue.

**Comment by k-doering-NOAA** [comment]
Added a PR template to nmfs-stock-synthesis/stock-synthesis. We could also add issue templates, if we thought they were useful.
