### ISSUE TITLE
triage issues

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/workflows#18]
Do this in the new year, after the 3.30.19 release. Triage issues esp. in the Stock Synthesis repo, although triaging issues in the other nmfs-stock-synthesis repos would be helpful, also.

**Comment by k-doering-NOAA** [comment]
Having a meeting in March to triage stock-synthesis repo issues without a milestone. Using the new beta projects github feature should help facilitate this.

**Comment by iantaylor-NOAA** [comment]
This issue was focused on triage for 3.30.19. We can open another as needed for future triage needs.
