### ISSUE TITLE
name of r package for workflows

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/workflows#2]
I noticed there is already a package called [workflows on cran](https://cran.r-project.org/web/packages/workflows/index.html).  @kellijohnson-NOAA , do you think we should call the r package something else (maybe useworkflows , in the spirit of usethis?)

I think it would be ok to rename the r package but not the repo(?), but let me know if you think this is confusing.

**Comment by kellijohnson-NOAA** [comment]
This package isn't something we would ever put on CRAN, so imo I think it is fine to have the same name as a different package. I have previously been really confused when a package has a name that is different than the repository.
