### ISSUE TITLE
Installer for ss3?

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/workflows#20]
Yeah. You are right about that.
What I am looking for is a zip file that puts the exe into a specific folder and has a script that can be run to modify PATH to refer to that folder.

_Originally posted by @Rick-Methot-NOAA in https://github.com/nmfs-stock-synthesis/doc/issues/91#issuecomment-1025972852_

**Comment by k-doering-NOAA** [comment]
To me, this does sound worth exploring.

ADMB has an installer, of course; I wonder if we could use something similar. If I'm remembering correctly, no admin privilegesare needed to download ADMB?

**Comment by iantaylor-NOAA** [comment]
This can be subsumed into https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/449.
