### ISSUE TITLE
centOS 8 ss3 build failing

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/workflows#22]
Apparently this is happening because centOS 8 reached [end of life](https://www.centos.org/centos-linux-eol/). The solutions possible are:

1. Use a newer version of Centos
2. Deprecate the job and just build on Ubuntu latest (currently 20)

While 2. may be easier, we may still want to do 1. instead of or in addition to 2., as for some reason the ubuntu build seems not to work on all linux machines (e.g., just today it was reported that the ubuntu wasn't working on a linux server).

**Comment by iantaylor-NOAA** [comment]
I like option 1 too. 
I suspect that those linux users who are using the OS on their individual computers will generally be using new versions since upgrading the operating system is really easy (in my limited experience). Those who are using institutionally maintained servers may not be as up to date but the server maintainers could provide support for compiling from source if needed.

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA do you have any insight into what flavor of linux people use typically on local machines? I was hoping ubuntu (the github actions default). It occurred to me there are plenty of [linux docker images] (https://hub.docker.com/search?architecture=386&source=verified&type=image). The whole reason we used centOS 8 was mostly historical and that for some reason it seemed ubuntu would run binaries compiled using centOS, but the reverse wasn't true.

I'm now thinking maybe we should compile the Ubuntu version and put a note in the release, asking Linux users to let us know if the compiled version isn't meeting their needs. We could also try testing running on different OSes, but this seems like too much work given that the number of linux users is probably low.

**Comment by Rick-Methot-NOAA** [comment]
Let us definitely pose a question in the prerelease notes that will go to the whole VLAB list.  In that message we could refer to a VLAB forum post in which we state the same question, and for which we can collect the responses.

**Comment by k-doering-NOAA** [comment]
Great suggestion to use vlab, Rick!

**Comment by iantaylor-NOAA** [comment]
I was thinking the same as Rick. No point speculating when we could just ask for feedback about what folks are using (and possibly suggestions on how best to compile something that works across flavors).

**Comment by k-doering-NOAA** [comment]
sounds good! 

In the meantime, I'm going to just deprecate the centOS job and keep the ubuntu one.
