### ISSUE TITLE
move shiny selectivity tool from r4ss/shiny_selex to nmfs-stock-synthsis org

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/workflows#23]
I'm wondering if the codebase for the [Shiny selectivity app](https://github.com/r4ss/shiny_selex) should be moved to the nmfs-stock-synthesis repo.

Also, I think this app could be expanded beyond just showing selectivity patterns (e.g., showing time varying specifications), so perhaps we would want to consider renaming it, also.

**Comment by k-doering-NOAA** [comment]
Also, if we do decide to move it, I think @iantaylor-NOAA would actually need to be the one to transfer ownership, as he has the ability to create repos for both r4ss and nmfs-stock-synthesis.

**Comment by iantaylor-NOAA** [comment]
This makes sense to me.
However, does it make sense to move all of r4ss/r4ss over as well?
The biggest drawback that I see is folks would need to change from `install_github("r4ss/r4ss")` to `install_github("nmfs-stock-synthesis/r4ss")`?

**Comment by kellijohnson-NOAA** [comment]
For a while you could keep r4ss/r4ss as a mirror with a warning?

**Comment by k-doering-NOAA** [comment]
How would we do the "mirror" technically, Kelli? Should we move the r4ss repo to nmfs-stock-synthesis and then create a fork in r4ss/r4ss? or is there a better way?

**Comment by k-doering-NOAA** [comment]
I also wonder if there is a way to alert users when they use install_github("r4ss/r4ss") that the location has changed? Or maybe just a message when they load the package?

**Comment by iantaylor-NOAA** [comment]
@kellijohnson-NOAA, I like the first idea but would like to chat about details before making big changes. 

I scheduled a meeting with you and @k-doering-NOAA for March 1 at 10am (I'm on vacation next week) to discuss details of the move. If that time isn't good for either of you, feel free to reschedule it. Anyone else interested in this topic is welcome to join if they wish--just let me know.

**Comment by Rick-Methot-NOAA** [comment]
I trust the 4 of you to come up with a good approach.  I support the alignment under one github organization.

**Comment by kellijohnson-NOAA** [comment]
[Instructions from Azure on how to move repositories](https://docs.microsoft.com/en-us/azure/devops/repos/git/move-git-repos-between-team-projects?view=azure-devops)

**Comment by k-doering-NOAA** [comment]
Thanks, Kelli! There is also just a "transfer repository" button on github that probably keeps issues and everything...

**Comment by iantaylor-NOAA** [comment]
The shiny_selex repo has now been moved from the r4ss organization to https://github.com/nmfs-stock-synthesis/shiny_selex (via the "transfer repository" button that @k-doering-NOAA mentioned). 

It no longer appears in the r4ss organization, but the old URL https://github.com/r4ss/shiny_selex automatically forwards to the new location.

The online version still works: https://connect.fisheries.noaa.gov/shiny-selex-ss3/ and this command also still works: `shiny::runGitHub("shiny_selex", "r4ss", ref = "main")` to run the shiny app off of github even though it points to the old location.

However, the command `remotes::install_github('r4ss/shiny_selex')` produces the following error:
```
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner and repo name correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
```

We still now need to 
- [ ] update the links on nmfs-fish-tools so it doesn't depend on the github forwarding things (@k-doering-NOAA)
- [ ] update the README to link to https://connect.fisheries.noaa.gov/shiny-selex-ss3/ (it's linked elsewhere already)
- [ ] change the name of the repo from `shiny_selex` if it we think of something better.

I will open a separate issue about cleaning up the older repos in the r4ss organization and moving the r4ss repo to nmfs-stock-synthesis as well.

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA , I don't think I have write permissions for the nmfs-stock-synthesis/shiny-selex repo. Could you modify the permissions?

**Comment by iantaylor-NOAA** [comment]
Oops, all teams were at "read" status, which must be the default starting point. I matched the settings for the stock-synthesis repo.

**Comment by k-doering-NOAA** [comment]
Thanks @iantaylor-NOAA , I can make changes to the repo now.

I'm wondering if nmfs-stock-synthesis/ss3-helper would be a better name? Right now, it doesn't have any functionality besides selectivity, but in case other functionality is added in the future, I think this would be a better name.

Note right now that this is not an R package, so ss3-helper would be an acceptable name. If it does grow into an R package, though, it may need to change to ss3.helper or ss3Helper.

**Comment by kellijohnson-NOAA** [comment]
@k-doering-NOAA I think renaming it is a great idea but I vote for dropping ss3 from the name, making "helper" sufficient and workable whether it is an r package or not.

**Comment by Rick-Methot-NOAA** [comment]
like Kelli's suggestion

**Comment by k-doering-NOAA** [comment]
Sounds good.

Christine is getting me set up with a rstudio connect job, so I can manage the hosting part of this. 

If everyone is down with just helper, @iantaylor-NOAA , feel free to go and change the repo name.

**Comment by iantaylor-NOAA** [comment]
Repo name changed to "helper": https://github.com/nmfs-stock-synthesis/helper.
@k-doering-NOAA, after you update the links once again to the new name, I assume we can close this issue and focus on the remaining related tasks in #30 (the next ones are on me).
