### ISSUE TITLE
Move r4ss org into nmfs-stock-synthesis org.

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/workflows#30]
Continued from #23 . Based on a discussion with @kellijohnson-NOAA  and @iantaylor-NOAA  earlier this week we decided to do the following:

- [x] move over the r4ss/shiny-selex repo 
- [ ] Learn from this experience to decide the details of how to migrate r4ss
- [ ] Clean up other r4ss org repos that aren't used (e.g., r4ss::SS_utils can probably just be deleted; likely true for other repos)
- [ ] Move r4ss over to nmfs-stock-synthesis
- [ ] Announce move of r4ss in release notes
- [ ] Decide on strategy for redirecting folks to the new location of r4ss (e.g., looking at apps that depend on r4ss and letting them know about the change? Potentially forking the new location of r4ss back to the old and adding a message upon trying to download or use r4ss from the old location?

**Comment by k-doering-NOAA** [comment]
I think we should revisit this before the 3.30.20 release.

**Comment by iantaylor-NOAA** [comment]
Issue moved to r4ss: https://github.com/r4ss/r4ss/issues/815.
