### ISSUE TITLE
reduce number of ss3 compile runs in github actions

### ISSUE THREAD

**Issue by Rick-Methot-NOAA** [nmfs-stock-synthesis/workflows#32]
The github test runs for every push to the stock_synthesis code repo has grown to >10 and takes nearly an hour.  Would it be possible to reduce this to 3 (compile for windows, compile for unix, run using existing parameters).  Then invoke the remaining actions in a manually triggered request?

**Comment by k-doering-NOAA** [comment]
Feel free to reopen if more changes are desired, Rick!
