### ISSUE TITLE
Consider adopting ideas from FIMS workshop for github workflow

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/workflows#33]
The FIMS workshop brought up some useful ideas for working on Github and collaborate coding. It would be great to talk about adopting these for the SS3 team, perhaps at our next team meeting

- Reviewer checklists appears in a comment when a PR is opened (e.g., https://github.com/NOAA-FIMS/FIMS/pull/49#issuecomment-1079446728) (too complex for SS3)
- Set up github action that automatically labels issues or pull requests (e.g., the new request label or something to indicate it still needs triage) (not much value added)
- Protect the main branch so that no one can directly push to it. Instead, a PR must be opened and at least 1 reviewer must approve changes before merging is allowed. We kind of follow this informally already, but it may be helpful if we add newer contributors with push access who are less aware of our workflow. 
- nmfs-stock-synthesis/stock-synthesis#451
- Using VS code liveshare for collaborative coding. This might be a great tool for our team to learn how to work more in the SS3 codebase. The advantage is liveshare can be used from the browser; the disadvantage is there is a decent learning curve to setting up VS code if you want to use it locally as your IDE. ( this is just something to try out with our team in the future, no actino needed)

**Comment by k-doering-NOAA** [comment]
Leaving this as some future workflow ideas to evaluate, but other members of the ss3 team can feel free to close if these ideas don't seem necessary.

**Comment by kellijohnson-NOAA** [comment]
Closing as we have added some of this to SS3 already and the one remaining thought of naming conventions is now its own issue in stock-synthesis (see above).
