### ISSUE TITLE
create and store man/roxygen/templates

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nmfs-stock-synthesis/workflows#36]
Do others think that it is a good idea to store man/roxygen/templates for things like `@verbose` in this repository. I am not sure how this would work in practice but in theory it seems good to me. I wonder if any other organizations share documentation across packages? @k-doering-NOAA have you ever seen this before? Also, could we just create a GitHub action that upon any changes to man/roxygen/templates files a pull request would be opened in downstream packages that updated the files used?

**Comment by k-doering-NOAA** [comment]
I wonder if Tidyverse does something like this.

**Comment by iantaylor-NOAA** [comment]
I just looked at some tidyverse roxygen documentation and they don't seem to use @template.
However, they extensively use `@inheritParams` (e.g., at https://github.com/tidyverse/dplyr/blob/main/R/pull.R#L7-L8)

This approach is documented in 
* https://r-pkgs.org/man.html#inheriting-arguments and 
* https://cran.r-project.org/web/packages/roxygen2/vignettes/reuse.html

However, the r-pkgs reference notes a possible problem with sharing documentation across packages: 
> You can inherit documentation from a function in another package by using the standard `::` notation, i.e. `@inheritParams anotherpackage::function`. This does introduce one small annoyance: now the documentation for your package is no longer self-contained and the version of `anotherpackage` can affect the generated docs. Beware of spurious diffs introduced by contributors who run `devtools::document()` with a different installed version of the inherited-from package.

My preference would be for each package to have self-contained documentation. If we ever put all of the SS3-related R packages into this one organization then we could revisit the approach.
@kellijohnson-NOAA if you're OK with that approach, we could close this issue or transfer it to ss3sim or r4ss if you think it should remain available.

**Comment by kellijohnson-NOAA** [comment]
@iantaylor-NOAA I have started using `@inheritParams` in some of my coding rather than `@template` because {tidyverse} guidelines suggested it but I haven't converted everything over. I think we can close this issue once we tick both boxes
- [x] open separate issues for {ss3sim} to suggest the use of `@inheritParams`
- [ ] open separate issue for {r4ss} to suggest the use of `@inheritParams`

**Comment by iantaylor-NOAA** [comment]
Issue added to r4ss and ss3sim
https://github.com/r4ss/r4ss/issues/814
https://github.com/ss3sim/ss3sim/issues/408
