### ISSUE TITLE
improve ss3 binary updating 

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/workflows#37]
continuation of #6.

Currently, the workflow should only be run manually when we know there are changes, as the version will be modified regardless of if there are changes are not. It would be nice to modify this so that no PR is opened if there is no difference between the current exe in ss3sim/SSMSE and the ones marked as the github latest release of ss3. That way, this can be run on a schedule instead of manually.

**Comment by kellijohnson-NOAA** [comment]
moved to https://github.com/ss3sim/ss3sim/issues/409
