### ISSUE TITLE
improve automation of routine tasks during PRs

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/workflows#43]
Usually to create the change log, information is gleaned by reading through each pull request with a certain milestone, and filling in the change log excel spreadsheet. It would be useful to automate this process more by having the reviewer write a description for each log entry on the pull request (or simply using the pull request title) and having the rest of the information autofilled into a table - like format that could be copied easily over to the excel sheet. From there, we may need to still read through and do some editing, but hopefully much less.

Edit: adding other steps that would be helpful to automated as part of the PR process:
- Change log creation
- opening doc, r4ss, and/or SSI issues resulting from the PR
- Linking the PR to a milestone
- Linking the PR to an issues using github's dropdown menu

**Comment by k-doering-NOAA** [comment]
I think improving automation of routine tasks could occur in 2 github actions. The next step would be mocking this up in a sandbox repo.

1. Upon opening a PR:
  - Link to the issue as provided within the template.  (this means that upon merging in the PR, the issue will be closed; this is usually, but not always appropriate, so we may need to consider carefully).
2. Upon merging a PR:
  - Open issues in doc, SSI, and r4ss repos, as the PR's first comment indicates.
  - Adds the change log info into the excel change log, as the PR's first comment indicates
  - Add the PR to the milestone we are currently working on

**Comment by k-doering-NOAA** [comment]
Working on mocking up the steps here: https://github.com/k-doering-NOAA/test_github_site/blob/main/.github/workflows/test-link-issue.yml

It's taking a little while because I'm having a hard time finding examples of exactly what I want to do, so figuring out the specification of the script through trial and error, but making progress. The most helpful links so far are: [documentation to the github api](https://docs.github.com/en/rest/pulls/pulls#update-a-pull-request) and [readme for this github-script action](https://github.com/actions/github-script)

**Comment by k-doering-NOAA** [comment]
https://github.com/nmfs-stock-synthesis/stock-synthesis/pull/345 opens a pull request with a workflow that will automatically open issues. Still to add on to this:

- [ ] Automatically adding a milestone to issues
- [ ] Automatically closing issues
- [ ] Automatically adding a milestone to the PR
- [ ] Updating the change log

**Comment by k-doering-NOAA** [comment]
Closing this since the work to automatically open issues was merged in and newer, more specific issues that could be worked one at a time were created.

**Comment by iantaylor-NOAA** [comment]
@k-doering-NOAA, it was a pleasure to see the new github action automatically create an issue: https://github.com/r4ss/r4ss/issues/713 upon merging this PR: https://github.com/nmfs-stock-synthesis/stock-synthesis/pull/349.

You noted in https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/348#issuecomment-1184849578 "The issues are created when the pull request is merged in rather than when it is created".

I wonder if it would be even more useful to create the issue in the other repo when the PR is first created, rather than when it's merged? The issue wouldn't necessarily need to be resolved in the other repository before the PR gets merged, but it could be useful to have an issue where discussion of the necessary changes could take place before the SS3 issue is completed.

**Comment by k-doering-NOAA** [comment]
Yes, we could change it if that seems better! The reason I did it on merge was that sometimes features change after the PR is opened, and I was thinking maybe the options of what needs to be updated may change...
However, I'm open to modifying the build trigger to be when the workflow is created, as I see what you mean!

**Comment by iantaylor-NOAA** [comment]
I reopened this issue in July to propose a refinement (opening issues in other repos like r4ss upon creation of the Pull Request that impacts them rather than after it gets merged). That refinement was added shortly thereafter but as usual I forgot to circle back to close the associated issue.
