### ISSUE TITLE
revise or generalize workflow related to r4ss code coverage test?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-stock-synthesis/workflows#45]
My recent attempt to clean up the testing for r4ss in https://github.com/r4ss/r4ss/pull/700 showed reduced coverage for a bunch of files because the executable isn't getting copied to the new smaller test model in this workflow file:
https://github.com/nmfs-stock-synthesis/workflows/blob/e596010cf5f015aa4982d54c2b391de5bd6aa0cb/.github/workflows/r4ss-extra-tests.yml#L79-L86

@k-doering-NOAA, would you suggest just adding a line for "simple_small" or somehow generalizing the copy command so that it works for whatever folders are present (except for the older 3.30.01 model which we could also just remove from the set)? I'm not sure the right sequence for changes here since the changes to r4ss are still in draft pull request form.

**Comment by k-doering-NOAA** [comment]
of course - you can make a branch in the workflows directory, perhaps, to test it in the r4ss branch? Then, after merging the r4ss branch into main, we can update the workflows main branch to copy to the correct folders?

**Comment by k-doering-NOAA** [comment]
Thanks for the reminder to look at this - I'm running again in https://github.com/r4ss/r4ss/actions/runs/2591418048 to see if the results are the same as your first run. That error is strange enough that I was wondering if it was an issue that might just fix itself...

**Comment by iantaylor-NOAA** [comment]
@k-doering-NOAA, I had an input file name error in the the test and your change helped find it, thank you.
I will leave this issue open until the r4ss branch gets merged and we then merge the workflows branch.

**Comment by iantaylor-NOAA** [comment]
This issue got sorted in June but I forgot to circle back to close it.
