### ISSUE TITLE
Automate creation of change log

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/workflows#46]
Continues https://github.com/nmfs-stock-synthesis/workflows/issues/43.

Automate the creation of the change log from the pull request. This could be added to https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/a12bfb143d4cd680ae9dc36ecc10cffeae395534/.github/workflows/ss3-pr-open-issues.yml or run as its own separate job. 

What we want to happen is on merging in the pull request:
1. Get info from the pull request body and figure out if the change log needs to be updated.
2. If the change log needs to be updated, read in the info for it. 
3. Read in the change log, edit, and read it out as modified.
4. Commit the change log (may need to be in a Pull Request, given our protected main branch?)

**Comment by kellijohnson-NOAA** [comment]
We are now using the project board for the change log.
