### ISSUE TITLE
Automate adding milestones and closing issues

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/workflows#47]
Continues #43.

Automate adding milestones to issues and closing issues upon merging in a pull request.

Examples of [adding a milestone and closing an issue](https://github.com/k-doering-NOAA/test_github_site/blob/main/.github/workflows/add-milestone-close-issue-gh-script.yml).

**Comment by e-gugliotti-NOAA** [comment]
@iantaylor-NOAA @kellijohnson-NOAA @Rick-Methot-NOAA - this is similar to the other automated milestones issue. If people use the tag in the PR such as "resolves #", "fixes #", and "closes #" then the issue should get closed when the PR is merged.

**Comment by e-gugliotti-NOAA** [comment]
Didn't mean to close issue.

**Comment by iantaylor-NOAA** [comment]
I worry a little bit that automating the assigment of milestones adds too much complexity to a task that is relatively simple to do manually. I think we could label this as wontfix and close.
