### ISSUE TITLE
Automate adding a milestone to a pull request

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/workflows#48]
Continues #43 .

Automate adding a milestone to a pull requests. Example here https://github.com/k-doering-NOAA/test_github_site/blob/main/.github/workflows/add-milestone-PR.yml, though we may want to just stick with using the gh r package for API calls instead.

**Comment by e-gugliotti-NOAA** [comment]
(trying to close out issues in workflow repo)
I don't know if automating adding a milestone to a PR is necessary especially in cases that a PR is a workflow or other small fix that isn't necessarily a part of a milestone. @kellijohnson-NOAA @Rick-Methot-NOAA @iantaylor-NOAA thoughts?

**Comment by Rick-Methot-NOAA** [comment]
Correct Kelli.  I think adding reminder to add to milestone and project board is good, but I do not think automation is necessary.
That said, I thought the approach we were using for project boards and milestones was to add the issue and let the GH system display the associated PR.  If we separately add the PR, then I think both will show up as separate entries.

**Comment by kellijohnson-NOAA** [comment]
I think this issue was created before we started the new system of putting most of the information in the issue and using the project board as the log so I think it can safely be closed without any follow-up action.

**Comment by Rick-Methot-NOAA** [comment]
Thanks Kelli.
Note that my recent research into the issue vs PR topic leads me to see an alternative:
a.  put scant info in the Issue, just as if it was submitted by someone on the outside as a request or bug report
b.  put all the substantive info in the PR
