### ISSUE TITLE
add additional R workflows  and r fxns to set them up

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/workflows#5]
- [x] reusable packagedown workflow (based on https://github.com/ss3sim/ss3sim/blob/main/.github/workflows/pkgdown.yaml)
- [x] building bookdown workflow (needed for SSMSE)
- [x] running document() workflow (would be used by all our R pkgs

We also want to create a basic R function like usethis does, so that users can easily set up to use the reusable workflow in their own R package that already exists.

**Comment by k-doering-NOAA** [comment]
@kellijohnson-NOAA , do you know of a repo that uses gh actions to build bookdown and deploy to gh pages? I'm having trouble getting the [r-lib example one](https://github.com/r-lib/actions/blob/master/examples/bookdown.yaml) working.

**Comment by k-doering-NOAA** [comment]
I have one working in SSMSE now: https://github.com/nmfs-fish-tools/SSMSE/blob/1d0dd45bc550f536564fb9e04532b1d5d8110656/.github/workflows/update-bookdown.yml

Will need to make more general (e.g., location of rmd files, where to render and deploy to ) for this repo

**Comment by kellijohnson-NOAA** [comment]
[This GitHub search](https://github.com/search?q=bookdown%3A%3Arender_book+path%3A.github%2Fworkflows+language%3AYAML+language%3AYAML&type=Code&ref=advsearch&l=YAML&l=YAML) came up with 505 examples. Where, [tidyverse has an example](https://github.com/tidyverse/style/blob/c26fc3ffbeb99567c9d64461f6954119d736896b/.github/workflows/bookdown.yaml) and [bioconductor has another example](https://github.com/Bioconductor/pkgrevdocs/blob/7ffc6e8a51bcdb48ad7f70b56fde84af9185f7e1/.github/workflows/build_deploy.yaml).

**Comment by k-doering-NOAA** [comment]
Closing this issue and opening a new one for improving the bookdown workflow.
