### ISSUE TITLE
trouble running github action on branch of r4ss

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-stock-synthesis/workflows#51]
@k-doering-NOAA, can you lend your github actions expertise to a problem I'm having?

I made changes in this r4ss branch https://github.com/r4ss/r4ss/tree/DM_changes_735 to work with the changes in Stock Synthesis associated with https://github.com/nmfs-stock-synthesis/stock-synthesis/pull/357.
In order to test the changes to r4ss with the changes to Stock Synthesis before both either branch gets merged, I tried to modify the associated workflow in this commit https://github.com/nmfs-stock-synthesis/workflows/commit/09b85384f5f9c0b126be83d40e6994e4ccd8f570 so that it uses the branch of r4ss.

However, after re-running the SS3 github action shortly after that change on Friday, and again today, I'm seeing that it continues to install the main branch of r4ss as shown in the screenshot below from https://github.com/nmfs-stock-synthesis/stock-synthesis/runs/7961590106?check_suite_focus=true#step:6:1.

Can you help me understand if I'm missing a step?

![image](https://user-images.githubusercontent.com/4992918/186023073-c8c00347-1bec-4071-9657-ca8894731bca.png)

**Comment by k-doering-NOAA** [comment]
For some reason, I think when hitting "rerun" on the job, it doesn't always incorporate new commits that were made. I don't quite get the nuances of this, but starting a fresh run (I triggered this manually) on the branch did the trick: https://github.com/nmfs-stock-synthesis/stock-synthesis/runs/7973420323?check_suite_focus=true

**Comment by iantaylor-NOAA** [comment]
Thank you @k-doering-NOAA. Manual trigger makes sense. I started a manual run and then cancelled it because I remember the re-run failed jobs option. However, it makes sense that "re-run" would be the identical job (such as for cases where there was problem with the action unrelated to your own code).
