### ISSUE TITLE
automatically delete merged branches throughout the nmfs-stock-synthesis organization?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-stock-synthesis/workflows#55]
GitHub has a setting to automatically delete merged branches, which would leave less clutter in the list of branches. Thanks to @kellijohnson-NOAA, this option was turned on for the FIMS project.

Instructions on implementing that option are here: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches

Are there any objections to me turning it on for all the nmfs-stock-synthesis repositories?

Responsibility still falls on us to manually clean up the stale branches that no longer have value.

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA I'm realizing this question was unaddressed! @e-gugliotti-NOAA and @Rick-Methot-NOAA, tagging you both for awareness to discuss. My personal opinion is automatically deleting merged branches is helpful for the reason Ian points out, but I think it is up to the team to decide if they like this preset.

**Comment by e-gugliotti-NOAA** [comment]
I like having the branches being deleted after merging. @Rick-Methot-NOAA or @iantaylor-NOAA - is there any reason why we would want to keep branches after merging?

**Comment by Rick-Methot-NOAA** [comment]
Just irrational fear of not being able to backtrack on a change.  I support auto-delete for 2023.

**Comment by k-doering-NOAA** [comment]
I also just looked into it, and you can always (no time limit) restore a deleted branch, so the branch is never lost if for some reason we do need it.

@e-gugliotti-NOAA , if we have time today during our meeting, maybe we could change the settings on the stock synthesis github repositories to auto delete branches.

**Comment by e-gugliotti-NOAA** [comment]
The instructions for restoring a branch that was deleted is available [here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/deleting-and-restoring-branches-in-a-pull-request).

**Comment by Rick-Methot-NOAA** [comment]
A situation in which a branch should be maintained is when there is an explicit Development Branch and an Operational Branch.  You would not want to auto delete the development branch.  I think Neal sometimes works a branch in that way.  @nschindler-noaa

**Comment by e-gugliotti-NOAA** [comment]
@nschindler-noaa, do you need to keep these branches after they have been merged onto the main branch? If you do, then we can always turn the setting back off.

**Comment by nschindler-noaa** [comment]
Not really. I can work either way. It is a bit of a pain to update the branch from main before doing additional work on a branch. So, auto deletion of branches is fine.

**Comment by iantaylor-NOAA** [comment]
Automatic deletion of merged branches is now turned on for all the repositories in the nmfs-stock-synthesis organization. That setting was already in place for most of them.
