### ISSUE TITLE
Use GitHub action input to set name of executable

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nmfs-stock-synthesis/workflows#56]
@k-doering-NOAA would you be okay if I used an [on.workflow_call.inputs](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onworkflow_callinputs) to set the name of the executable in this workflow. I would make the default name be "ss" so you wouldn't need to change anything for SSMSE but it would allow me to pass "ss3" in the caller workflow in {ss3sim}.

Associated with ss3sim/ss3sim#401

Then, the input could be used in the following lines to name the file.
https://github.com/nmfs-stock-synthesis/workflows/blob/dc85654e3f0bf225bde066e978d45b931d9825cc/.github/workflows/update-ss3-version.yml#L50-L52

https://github.com/nmfs-stock-synthesis/workflows/blob/dc85654e3f0bf225bde066e978d45b931d9825cc/.github/workflows/update-ss3-version.yml#L59-L60

**Comment by k-doering-NOAA** [comment]
go for it! Let me know if you run into any issues. 

I think there are some examples in this repo and ghactions4r of setting up the inputs.
