### ISSUE TITLE
update workflows that use set-output

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/workflows#62]
Workflows (e.g.,https://github.com/nmfs-stock-synthesis/workflows/blob/85f79236758b28469b756acd5d3c92e9615b5c25/.github/workflows/update-ss3-version.yml#LL32C11-L33C69) in this repo use set-output, which will be deprecated by github in mid 2023. For now, a warning is generated on the github action runs that have not been updated.

All that needs to be done is that the set-output lines need to be changed slightly. For example, 
```
echo "::set-output name=link_to_release::${link_to_release}"
```
should be changed to
```
echo "link_to_release=$link_to_release" >> $GITHUB_OUTPUT
```
(EDIT: curly braces around `link_to_release` are optional, so I removed them!)

An example of the change in another repo: https://github.com/noaa-fisheries-integrated-toolbox/toolbox_web_templating/commit/076a2ae87369593955a57a7480833eb74071fe31

See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ for more details.

@e-gugliotti-NOAA is this something you could work on?

**Comment by e-gugliotti-NOAA** [comment]
Yes, I can work on this. I've changed all the occurrences I see but I do
have a couple questions that I can ask you about tomorrow.

*Elizabeth F. Gugliotti (she/her)*
---

*Research Associate*

ECS Federal contracted to

NOAA/NMFS/National Stock Assessment Program

Mobile: 843-469-1074

**Comment by k-doering-NOAA** [comment]
Thanks, and sounds good!

**Comment by e-gugliotti-NOAA** [comment]
@k-doering-NOAA can you relink that nmfs toolbox example? That might help me with the current issue because it's with an output call later on, not the initial place that we thought might be causing the error due to spacing.

**Comment by k-doering-NOAA** [comment]
I just gave you read permissions to the toolbox repo, I forgot it is set to private! Here is the [toolbox example](https://github.com/noaa-fisheries-integrated-toolbox/toolbox_web_templating/commit/076a2ae87369593955a57a7480833eb74071fe31) again. 

My guess is windows is not parsing the  new output correctly, because it is working just fine on linux and mac. Seems like a github actions bug. ([more info on using output parameters](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter)). I had an issue with one of the actions in ghactions4r that was similar.

**Comment by k-doering-NOAA** [comment]
I posted this discussion, hopefully so we can get some help: https://github.com/orgs/community/discussions/42790

**Comment by e-gugliotti-NOAA** [comment]
Okay great! Yes, hopefully someone in the community will have an answer for
us!

*Elizabeth F. Gugliotti (she/her)*
---

*Research Associate*

ECS Federal contracted to

NOAA/NMFS/National Stock Assessment Program

Mobile: 843-469-1074
