### ISSUE TITLE
improve documentation/functions to use ss3 workflows

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/workflows#8]
Need to improve documentation on the different stock synthesis workflows available and how to use them.

**Comment by iantaylor-NOAA** [comment]
Workflows are thoroughly documented by @k-doering-NOAA in [this Google Doc](https://docs.google.com/document/d/1hniPVEobdzEQqdIsAiHavZgze70TgGQzYiwP7T4SUWw/edit#heading=h.m8zwkqanwdq0) which is linked from the workflows repo README.
